package git

import "errors"

var (
	ErrRepositoryNotFound        = errors.New("repository not found")
	ErrCloneFailed               = errors.New("failed to clone repository")
	ErrPullFailed                = errors.New("failed to pull repository")
	ErrBranchNotFound            = errors.New("branch not found")
	ErrTagNotFound               = errors.New("tag not found")
	ErrFileNotFound              = errors.New("file not found")
	ErrInvalidRepository         = errors.New("invalid repository")
	ErrAuthenticationFailed      = errors.New("authentication failed")
	ErrRepositoryAlreadyExists   = errors.New("repository already exists")
	ErrCleanupFailed             = errors.New("failed to cleanup repository")
	ErrValidationFailed          = errors.New("repository validation failed")
	ErrTimeout                   = errors.New("operation timeout")
	ErrDiskSpace                 = errors.New("insufficient disk space")
	ErrOperationCancelled        = errors.New("operation cancelled")
	ErrBranchCreateFailed        = errors.New("failed to create branch")
	ErrBranchDeleteFailed        = errors.New("failed to delete branch")
	ErrBranchSwitchFailed        = errors.New("failed to switch branch")
	ErrBranchMergeFailed         = errors.New("failed to merge branch")
	ErrTagCreateFailed           = errors.New("failed to create tag")
	ErrTagDeleteFailed           = errors.New("failed to delete tag")
	ErrTagVerificationFailed     = errors.New("tag verification failed")
	ErrBranchAlreadyExists       = errors.New("branch already exists")
	ErrTagAlreadyExists          = errors.New("tag already exists")
	ErrInvalidBranchName         = errors.New("invalid branch name")
	ErrInvalidTagName            = errors.New("invalid tag name")
	ErrCannotDeleteDefaultBranch = errors.New("cannot delete default branch")
	ErrMergeConflict             = errors.New("merge conflict detected")
	ErrRemoteOperationFailed     = errors.New("remote operation failed")
)
