// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://apiarycd.com/support",
            "email": "support@apiarycd.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/stacks": {
            "get": {
                "description": "Retrieve a list of all configured stacks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stacks"
                ],
                "summary": "List all stacks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/stacks.StackResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new Docker Swarm stack with the provided configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stacks"
                ],
                "summary": "Create a new stack",
                "parameters": [
                    {
                        "description": "Stack creation request",
                        "name": "stack",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/stacks.POSTRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/stacks.StackResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stacks/{id}": {
            "get": {
                "description": "Retrieve details of a specific stack by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stacks"
                ],
                "summary": "Get a specific stack",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/stacks.StackResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing stack by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stacks"
                ],
                "summary": "Delete a stack",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an existing stack with the provided fields",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stacks"
                ],
                "summary": "Update a stack",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Stack update request",
                        "name": "stack",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/stacks.PATCHRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stacks/{id}/deploy": {
            "post": {
                "description": "Trigger a deployment of a stack",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stacks",
                    "deployments"
                ],
                "summary": "Deploy a stack",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Deployment request",
                        "name": "deploy",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/stacks.POSTDeployRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/stacks.DeploymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stacks/{id}/history": {
            "get": {
                "description": "List all deployments for a stack",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stacks",
                    "deployments"
                ],
                "summary": "List deployments for a stack",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/stacks.DeploymentResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stacks/{id}/rollback": {
            "post": {
                "description": "Rollback a stack to a previous version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stacks"
                ],
                "summary": "Rollback a stack",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/stacks.DeploymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "deployments.Status": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "success",
                "failed",
                "cancelled",
                "rolled_back"
            ],
            "x-enum-comments": {
                "StatusCancelled": "Deployment was cancelled",
                "StatusFailed": "Deployment failed",
                "StatusPending": "Deployment has not started",
                "StatusRolledBack": "Deployment was rolled back",
                "StatusRunning": "Deployment is in progress",
                "StatusSuccess": "Deployment completed successfully"
            },
            "x-enum-descriptions": [
                "Deployment has not started",
                "Deployment is in progress",
                "Deployment completed successfully",
                "Deployment failed",
                "Deployment was cancelled",
                "Deployment was rolled back"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusRunning",
                "StatusSuccess",
                "StatusFailed",
                "StatusCancelled",
                "StatusRolledBack"
            ]
        },
        "fiberfx.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_apiarycd_apiarycd_internal_server_handlers_stacks.GitAuth": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "format": "password"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "stacks.DeploymentResponse": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "description": "When deployment completed/failed",
                    "type": "string"
                },
                "created_at": {
                    "description": "Timestamps",
                    "type": "string"
                },
                "error": {
                    "description": "Error message if failed",
                    "type": "string"
                },
                "git_ref": {
                    "description": "Branch, tag, or commit",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "logs": {
                    "description": "Logs and Metrics",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "description": "Git commit message",
                    "type": "string"
                },
                "previous_deployments": {
                    "description": "Rollback Information",
                    "type": "string"
                },
                "stack_id": {
                    "description": "References",
                    "type": "string"
                },
                "started_at": {
                    "description": "When deployment started",
                    "type": "string"
                },
                "status": {
                    "description": "Status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/deployments.Status"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                },
                "variables": {
                    "description": "Deployment Configuration",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "version": {
                    "description": "Deployment Details",
                    "type": "string"
                }
            }
        },
        "stacks.PATCHRequest": {
            "type": "object",
            "properties": {
                "compose_path": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "git_auth": {
                    "$ref": "#/definitions/github_com_apiarycd_apiarycd_internal_server_handlers_stacks.GitAuth"
                },
                "git_branch": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "git_url": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "stacks.POSTDeployRequest": {
            "type": "object",
            "properties": {
                "variables": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "stacks.POSTRequest": {
            "type": "object",
            "required": [
                "compose_path",
                "git_branch",
                "git_url",
                "name"
            ],
            "properties": {
                "compose_path": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "git_auth": {
                    "$ref": "#/definitions/github_com_apiarycd_apiarycd_internal_server_handlers_stacks.GitAuth"
                },
                "git_branch": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "git_url": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "stacks.StackResponse": {
            "type": "object",
            "required": [
                "compose_path",
                "git_branch",
                "git_url",
                "name"
            ],
            "properties": {
                "compose_path": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "git_branch": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "git_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "last_deploy": {
                    "type": "string"
                },
                "last_sync": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ApiaryCD API",
	Description:      "ApiaryCD is a GitOps platform for managing Docker Swarm stacks",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
